"use client"
import Head from "next/head";
//import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useBulletContext } from "@/api/bulletContext";
import SpawnBullets from "./components/spawnbullets";import SpawnEnemys from "./components/spawnEnemys";
 './components/spawnBullets'

//const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { bulletsList, createBullet } = useBulletContext();

  const handleClick = (event: any) => {
    const posX = event.clientX;
    createBullet(posX)
  };

  return (
    <>
      <Head>
        <title>Space Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} onClick={handleClick}>
        <div className={styles.space}>
          <div className={styles.enemySpace}>
            <SpawnEnemys />
          </div>
          <div className={styles.heroSpace}></div>
          <SpawnBullets />
        </div>
      </main>
    </>
  );
}
